inherit_from: https://raw.githubusercontent.com/discourse/discourse/master/.rubocop.yml

# https://github.com/rubocop-hq/rubocop/issues/1518
Lint/ShadowingOuterLocalVariable:
  Enabled: false

Layout/AlignHash:
  Enabled: false
