name: DDNS-SD Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    env:
      PGHOST: localhost
      PGUSER: admin
      PGPASSWORD: admin
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: ["2.7", "2.6", "2.5"]
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: admin
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Bundler cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ matrix.ruby }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ruby }}-gems-
      - name: Setup gems
        run: |
          gem uninstall bundler
          gem install bundler -v 2.1.4
          bundle config path vendor/bundle
          bundle install --jobs 4
      - name: Migrate DB
        run: bundle exec rake test:prepare
      - name: Tests
        run: bundle exec rspec
      - name: Rubocop
        run: bundle exec rubocop
